<?php
/**
 * Created by PhpStorm.
 * User: tanzhenxing
 * Date: 2018/4/2
 * Time: 11:12
 */
namespace app\admin\controller;

use think\Controller;
use app\base\model\Site;
use app\base\model\Admin;

class AdminBase extends Controller
{
    protected $site_id;
    protected $template_path;

    /**
     * 管理员模板初始化数据
     * @throws \think\exception\DbException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $login_url = '/admin/login/index'; // 后台登录网址
        // 获取当前域名是否授权
        $get_domain = $this->request->host();
        $get_domain = preg_replace('/www./', '', $get_domain);
        $site_info = Site::get(['domain'=>$get_domain]);
        if(empty($site_info)) {
            $this->error('欢迎使用培训分销系统，您的网站还没有开通，请联系电话：13450232305',$login_url);
        }

        $this->assign('site',$site_info);
        $this->site = $site_info;

        // 获取site_id
        $site_id = $site_info['id'];
        $this->site_id = $site_id;

        // 判断是否有管理网站的权限
        $admin_username = session('username');
        $admin_data = Admin::get(['username'=>$admin_username]);
        $my_admin_id = $admin_data['id'];
        if($site_info['admin_id'] != $my_admin_id){
            $this->error('您没有管理该网站的权限',$login_url);
        }

        // 后台模板路径
        $module_name = $this->request->module();
        $controller_name = $this->request->controller();
        $action_name = $this->request->action();

        $template_path = '/' . $module_name .'/pc/'.$controller_name.'/'.$action_name;
        $template_path = strtolower($template_path);
        $this->template_path = $template_path;

        $template_public_header = '/' . $module_name .'/pc/public/header';
        $template_public_footer = '/' . $module_name .'/pc/public/footer';
        $this->assign('public_header',$template_public_header);
        $this->assign('public_footer',$template_public_footer);


    }
}