<?php
/**
 * Created by PhpStorm.
 * User: tanzhenxing
 * Date: 2018/5/8
 * Time: 16:24
 */
namespace app\agent\controller;

use app\common\model\Agent;
use think\Controller;
use app\base\controller\Template;

class AgentBase extends Controller
{
    protected $template_path;

    /**
     * @throws \think\exception\DbException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $login_url = '/agent/login/index'; // 后台登录网址

        // 判断是否有管理网站的权限
        $agent_username = session('agent_username');
        $admin_data = Agent::get(['username'=>$agent_username]);
        if(empty($admin_data)){
            $this->error('您还没有登录',$login_url);
        }

        // 模板路径
        $public_array = array('public_header'=>'/public/agent_header','public_footer'=>'/public/agent_footer');
        $template = new Template();
        $template_path = $template->path($public_array);
        $this->template_path = $template_path;

    }
}