<?php
/**
 * Created by PhpStorm.
 * User: tanzhenxing
 * Date: 2018/5/2
 * Time: 17:00
 */
namespace app\base\controller;

use think\Controller;

class TraderAdminBase extends Controller
{
    protected $site_id;
    protected $template_path;
    protected $site;

    /**
     * @throws \think\exception\DbException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $site_data = new Site();
        $site_info = $site_data->info();
        $this->assign('site',$site_info);
        $this->site = $site_info;

        $this->site_id = $site_info['id'];
        $this->assign('site_id',$site_info['id']);

        // 后台模板路径
        $template = new Template();
        $template_path = $template->path();
        $this->template_path = $template_path;
    }
}