<?php
/**
 * Created by PhpStorm.
 * User: tanzhenxing
 * Date: 2018/4/4
 * Time: 16:31
 */
namespace app\machong\controller;

use app\machong\model\Setting;
use think\Controller;

class Base extends Controller
{
    /**
     * 公用信息
     * @throws \think\exception\DbException
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        // 网站基本信息
        $data = new Setting();
        // 首页名称
        $site = $data->where(['valuename'=>'indexname'])->find();
        $index_name = $site['valuetxt'];
        $this->assign('index_name',$index_name);

        // 网站url
        $site_url_data = $data->where(['valuename'=>'siteurl'])->find();
        $site_url = $site_url_data['valuetxt'];
        $this->assign('site_url',$site_url);
    }
}